id: multilabel
key: MT::Plugin::Multilabel
name: Multilabel
version: 0.1
description: <MT_TRANS phrase='description of Multilabel'>
author_name: Takuji Tokiwa
author_link: http://www.allianceport.jp/
l10n_class: Multilabel::L10N
config_template: config_template.tmpl
schema_version: 0.04
settings:
    multilabel_class:
        default: ja,en,cn,kr
object_types:
    multilabel: Multilabel::Object
    multilabel_data: Multilabel::ObjectData
listing_screens:
    multilabel:
        primary: keyword
        screen_label: multilabel
        object_label: multilabel
        object_label_plural: multilabels
        default_sort_key: id
        view:
            - system
            - website
            - blog
        scope_mode: wide
        condition: sub { return 1 }
list_properties:
    multilabel:
        id:
            auto: 1
            label: ID
            order: 10
            default_sort_order: aescend
        keyword:
            auto: 1
            label: Keyword
            order: 11
            display: force
            default_sort_order: aescend
            html_link: $Multilabel::Multilabel::List::html_link
        class:
            auto: 1
            label: class
            order: 12
            display: force
            default_sort_order: aescend
list_actions:
    multilabel:
        delete:
            label: Delete
            code: $Multilabel::Multilabel::List::delete
            order: 100
            js_message: delete
            button: 1
applications:
    cms:
        menus:
            multilabel:
                label: Multilabel
                order: 410
            multilabel:list:
                label: Manage
                order: 1
                view:
                    - system
                    - website
                    - blog
                mode: list
                args:
                    _type: multilabel
                condition: sub { return 1 }
            multilabel:view:
                label: New
                order: 2
                view:
                    - system
                    - website
                    - blog
                mode: multilabel_view
                args:
                    _type: multilabel
                condition: sub { return 1 }
        compose_menus:
            compose_menus:
                menus:
                    multilabels:new:
                        label: Multilabel
                        order: 250
                        view:
                            - system
                            - website
                            - blog
                        mode: multilabel_view
                        args:
                            _type: multilabel
                        condition: sub { return 1}
        methods:
            multilabel_view: $Multilabel::Multilabel::CMS::view
            multilabel_save: $Multilabel::Multilabel::CMS::save
            multilabel_delete: $Multilabel::Multilabel::CMS::delete
tags:
    function:
        MultilabelText: $Multilabel::Multilabel::ContextHandlers::hdlr_tag
    block:
        Multilabel: $Multilabel::Multilabel::ContextHandlers::hdlr_container
